### ISSUE TITLE
Fishbot not clicking on the bobber

### ISSUE THREAD

**Issue by SeussCZ** [UltimateFishbot/UltimateFishbot#100]
Hello, i have a issue, when all is set up, and i press START, cursor dont stop on the bobber. How to fix it? I play on wow 4.3.4

**Comment by juggenizer** [comment]
I can verify this and also verified fix for it. For all occurances of IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft"); You should change to IntPtr Wow = FindWindow(null, "World Of Warcraft");

After that everything works, this was also a issue where the "click/loot" didn't work because of this

**Comment by NaNraptor** [comment]
Fixed in latest version
