### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by gorskorr** [UltimateFishbot/UltimateFishbot#130]
Pretty wet behind the ears when it comes to programming. If anyone could shed some light on how I can fix this build error I'd be very appreciative.

1>------ Build started: Project: UltimateFishBot, Configuration: Debug Any CPU ------
1>C:\UltimateFishbot\UltimateFishbot-CSharp\UltimateFishBot\Program.cs(20,26,20,40): error CS1061: 'LoggerSinkConfiguration' does not contain a definition for 'ColoredConsole' and no accessible extension method 'ColoredConsole' accepting a first argument of type 'LoggerSinkConfiguration' could be found (are you missing a using directive or an assembly reference?)
1>C:\UltimateFishbot\UltimateFishbot-CSharp\UltimateFishBot\Forms\frmMain.cs(159,35,159,37): warning CS0168: The variable 'ex' is declared but never used
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

This is from the most up to date files here, and the currently available MSV

**Comment by NaNraptor** [comment]
That usually happens when you try and update the nuget packages to latest version OR do not have any packages installed.

Go to project - > manage nuget packages - > Restore

The restore button should be a great big yellow thing :) 

If that doesn't work it means I have screwed up somewhere while committing the source and will look into it more deeply

UPDATE: I just tested it and was able to compile successfully after restoring NuGet packages

**Comment by Lunat1q** [comment]
That can happen if you use latest logging library, not the one referenced in the project.

**Comment by NaNraptor** [comment]
I have found that if you update only Fody and nothing else this issue happens again - literally no idea why. Putting that here as additional information.

Closing the issue as no input from @gorskorr
