### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by VXNerve** [UltimateFishbot/UltimateFishbot#152]
the Ultimate Fishbot Dev Release 4.1(01) works perfectly, the only problem I'm experiencing is a delay when the bobber goes down, the bot only says there is a fish 1 second after the bobber fails and the threshold for sound is at 16, I did test the cast sounds etc and everything was done right, so far I know. And the two releases after Dev Release 4.1(01) doesn't cast, the cursor freaks out and jumps off the windowed wow and doesn't want to start scanning the scanned area for the bobber. This is everything I've encountered so far.

**Comment by NaNraptor** [comment]
In terms of the the delay, make sure you change the delay setting around.

As the newer versions not working, unfortunately it is known that the bot just doesn't work with some pcs for some strange reason. We have not been able to fix it and since it affects a fairly small amount of people I personally decided not to spend loads of time trying to fix it.

Sorry for any inconvenience that this causes.
