### ISSUE TITLE
WoD Bait not working

### ISSUE THREAD

**Issue by matheous** [UltimateFishbot/UltimateFishbot#38]
Everything works great. It was able to help me with my fishing skill. However, the WoD bait is bugged. It never adds bait. And since each type of bait is a unique item, we can only have one so trying to reapply every 5min wouldn't work unless it can detect or have a list of baits to choose from. That would be cool.

**Comment by henrikhermansen** [comment]
Do you use the random bait feature, or just one particular bait? Do you fish in your garrison or in a particular zone?

**Comment by matheous** [comment]
I didn't know there was a random bait feature. I keep trying to put the bait in the spot it goes with alt 6 just like the other 1-5 alts that work fine. I have tried fishing in many zones.

**Comment by henrikhermansen** [comment]
I just tested this myself with Alt-Key modifiers and the WoD Bait Key 1 set to 6. Both Lure, Raft, Bait and Cast worked fine with Alt-Key modifiers. Make sure you have checked the box "Apply Bait Every 5 minutes", and not checked the box "Random bait between the 7 possibles". If you've done these things, try to disable Alt-Key modifier and Apply Bait, save it, and re-enable them again before you finally save it again. Also make sure you only have "6" in the WoD Bait Key 1 input field. Finally, when you try to run the bot again, take note of what the fishbot is saying. Have WoW in windowed mode and place the fishbot so that you can see the area where the bot reports what it's doing. Let me know how this works out :)

**Comment by henrikhermansen** [comment]
In regards to your concerns about bait and re-applying it every 5 mins: you're right that bait is unique, however that means it's unique in your inventory. Once you apply bait you may catch that same bait right away. Bait has a 20% drop chance in open waters, meaning you gotta be really unlucky not to get a new bait before you need to re-apply it. I've fished for hours on and never noticed that I've been without active bait. Note that pools don't drop bait, and the drop chance for each bait is lower in garrison. Read more about bait on http://www.elsanglin.com/bait_and_fillet.html and http://www.elsanglin.com/garrison_fishing.html

**Comment by Alpheratz57** [comment]
You are talking about a "Random bait between the 7 possibles". As of now, we just can't see this option. Are you sure that the compiled release is the same of the source code shown there ?
This is my options : 
Cast Key = 0 
Lure Key = 1
Wod Bait Key = 6
Use Alt-Key Modifier = checked
Apply Lure Every 10 minutes = checked
Apply Bait Every 5 minutes = checked
Else unchecked of left empty
The pgm never applies either bait or lure, but fish perfectly. I also tried with all add-on desactivated. Nothing changes. My Wow is localised and so not in english

**Comment by henrikhermansen** [comment]
Oh, that's my mistake. I didn't really consider that the random bait had not yet been compiled and released on the website. Thus I can't really know whether the alt-key modifier worked in that version. I added the initial bait functionality, and later someone else added the expanded functionality for random bait. So to be honest I have a strong feeling I didn't verify that the alt-key modifier worked for the bait, but apparently it works now with the latest code. To help the guy in #29 I compiled and released the latest code at http://www.henrikh.net/fishbot_3_1.zip. Note that this is not an official version, I just named it 3.1 as it contains all the latest code since 3.0. Try downloading that version and see if it helps you.
PS! I doubt the localization of your WoW matters as the bot never really interacts directly with the WoW process.

**Comment by Alpheratz57** [comment]
There's some improvements ! Indeed luring now works perfectly. It starts applying one and then refresh it after 10 minutes, that's ok
But ... bait applying still doesn't work. I tried all combinations of checkking/unchecking "Aplpy Bait Every 5 minutes" and "Random bait betweeen the 7 possibles". When sould i expect the bait applied ? At the begining ? or after 5 mn ? ( at this point, same result : nothing happens)

**Comment by henrikhermansen** [comment]
Watch what the bot says when you start it. When you push start, and got lure, raft and bait enabled, it should say "Starting", "Applying lure...", "Applying raft...", "Applying bait...", and finally "Casting...". Then it should cast and say "Waiting for bobber..." while it searches for the bobber, and finally "Waiting for fish..." while it's waitig for the fish to bite. Obviously it's the things it says between "Starting" and "Casting..." you want to take note of to make sure it attempts to do all the things it should do. If you have either lure, raft or bait disabled it should obviously skip that step, and do the other steps in the same order.

**Comment by SpencerCarstens** [comment]
Before creating another posting, I thought I would ask here to make sure I'm not missing something.

Is it possible to have the bot go through all possible bait, one by one?

There is a random option I know, but unsure if it would randomly do the same or previously used slot over again.

My goal is to use this for garrison fishing, as you cannot find more bait when fishing there, yet you may use any bait. So going through each type of bait would be a good way to get a assortment of each fish in one run without having to change locations.

Thank you for your time.

**Comment by henrikhermansen** [comment]
@SpencerCarstens that would be possible, for sure. Feel free to open a new issue with this suggestion, so we can track it separately from this issue.

**Comment by pladesmeden** [comment]
I still have an issue with wod bait, it will simply not apply it, have tryed anything, the bot is saying "apply bait" but its not pushing the buttom.

**Comment by juggenizer** [comment]
I think i might know what the problem with the bait is, and i can maybe fix it. I think its because the program starts the cycle on "0". When you see "Applaying bait 0". Maybe the bait intervall starts at 1? I'll check it out. At least it works if you check the box "Cycle through the 7 possible baits".

**Comment by NaNraptor** [comment]
Most likely fixed in latest version, if not reopen the issue
