### ISSUE TITLE
Cycle through all bait option.

### ISSUE THREAD

**Issue by SpencerCarstens** [UltimateFishbot/UltimateFishbot#44]
Can we please get an option to cycle through all available WoD bait?

My goal is to use this for garrison fishing. When fishing in your garrison you cannot find more bait, yet you may use any bait you please. So going through each type of bait would be a good way to get a assortment of each fish in one run without having to change locations.

Thank you for your time.

**Comment by Mograine** [comment]
Hello,

Actually you can catch new bait while fishing in your garrison, there is just lower chances, the random bait was implemented because of garrison fishing, and it's rare when after a fishing night a bait is missing in my bags.

But it would in fact be more efficient to go through each type of bait, so i think i will just replace the random bait by this option.

**Comment by henrikhermansen** [comment]
I agree with your suggested solution @Mograine . And to add some info on bait: The chance of getting bait alongside your catch is about 20% in zones and 4% for each of the bait types in your garrison.

**Comment by SpencerCarstens** [comment]
Ah, you guys are totally right. I misread this.

http://www.elsanglin.com/garrison_fishing.html

Thanks!
