### ISSUE TITLE
Doesn't reel in after splash.

### ISSUE THREAD

**Issue by epx998** [UltimateFishbot/UltimateFishbot#66]
Seems to work, minus reeling in after hooking a fish.  Any ideas?

**Comment by epx998** [comment]
I got it working by checking the default output to ensure the device was being heard by the app, then casted a few times to see what level was detected and adjusted accordingly.  Cheers.

**Comment by LaBlazer** [comment]
Good to hear that, closing the issue...

**Comment by klaxce** [comment]
I was actually having this exact issue yesterday, and came back here to see if it had been resolved. If you want me to open a new ticket, let me know.

Fishbot-4.1.01
I spent about 2 hours on this, trying on both Win 10 x64, and Win 7 x64 (desktop, laptop). Took a while to get the scanning and cursor detection to work, but now it won't reel in/click after splash audio (Win 7, never got 10 to detect properly).

I set WoW to output to speakers, set Fishbot to speakers, had "background audio" enabled, and threw the fishing line, hearing the splash, and seeing the sound detection in Fishbot. However, it doesn't matter if I turn the game audio to max, set windows audio to max, and set the Fishbot detection to "1", it misses every single splash. It doesn't even look like it wrongfully "clicks", it doesn't do it at all.

I could sit there and just click everytime I heard the splash and it worked, as detection was good about 80% of the time, but that was it.

Let me know what else you need in order to assist. Thanks
