### ISSUE TITLE
Fishes don't get looted

### ISSUE THREAD

**Issue by Gamala** [UltimateFishbot/UltimateFishbot#90]
When I use the bot it opens the fish but don't loot it, and I tried having auto-loot on/off + the feature in settings for those who don't use auto-loot, but still doesn't work?

**Comment by juggenizer** [comment]
I can verify this and also verified fix for it. For all occurances of IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft"); You should change to IntPtr Wow = FindWindow(null, "World Of Warcraft");

After that everything works, this was also a issue where the "click/loot" didn't work because of this

**Comment by mcousins2009** [comment]
With all the change is someone brave enough to do a dev release so I can do and test with the last dozen or so changes?

**Comment by juggenizer** [comment]
Idk mate, I can send you my build that should work. Also changed the name of the process, pretty stupid to have anything with "bot" in the name, because of the blizzard warden. I also tend to change things in the code before i will use it for a long time, and re-build. Not sure if it avoids the blizzard warden RAM scan but i still haven't been caught at least :P 
Here is my build https://www.dropbox.com/s/5jafn0z0zx4y37o/Debug.zip?dl=0

**Comment by NaNraptor** [comment]
You should have Auto Loot enabled in WoW, or the Shift-Loot tickbox ticked within the bot settings
