### ISSUE TITLE
possible solution for the bot ignoring the cursor

### ISSUE THREAD

**Issue by nengoxx** [UltimateFishbot/UltimateFishbot#92]
I've read some of the bug reports and in some cases the bot doesn't recognize the cursor, I found In the source that the icon you search for is not the 'gear' icon but the regular fishing icon, I don't know if it's a version or private server issue but adding/replacing the gear icon may solve the problem. I don't know how to get the gear icon from the game though.

**Comment by Sval-venia** [comment]
If you have the latest version of fish bot, go to settings and under "Finding the cursor" tab you'll see a check box towards the bottom with "Check Cursor Icon" that has the box next to it checked off.

Un-check this box and the program should run normally afterwards.

**Comment by juggenizer** [comment]
I can verify this and also verified fix for it. For all occurances of IntPtr Wow = FindWindow("GxWindowClass", "World Of Warcraft"); You should change to IntPtr Wow = FindWindow(null, "World Of Warcraft");

After that everything works, this was also a issue where the "click/loot" didn't work because of this

**Comment by NaNraptor** [comment]
Issue has been solved multiple times already, closing.
