### ISSUE TITLE
Won't cast fishing

### ISSUE THREAD

**Issue by antlanggam** [UltimateFishbot/UltimateFishbot#93]
hello I tried the bot out the fishing key has been already set to 1 but It doesn't cast fishing  it just starts finding the bobber. is there any way to fix this?

**Comment by Sval-venia** [comment]
I had this problem too, and what I found is that I had to raise my "master volume" in the game to roughly 40% (30% before). Ensure that the sound output is the same within the game as well as for what Fishbot is set to.

To test if fishbot is hearing sound from the right output device, go to settings  and click on the "hearing the fish". Under audio device, watch the bar to the right of the drop down menu when playing a youtube video or something to get an idea of how loud it's detecting sound through your PC and then tailor your "Splash Threshold" accordingly.

NOTE: No matter how low you put the threshold, or how high your desktop sound is, if your "Master Volume" found in the "Sound" section of your system settings within the game is too low, the program will not be able to "hear" the fish effectively.

Hope this helped.

**Comment by beldjinn** [comment]
i have the same problem, i put master volume at 100%; sound 100%, music and ambiance 0%. My fishing pole is equiped, and my fish spell on the first slot of my action barre1 binding by this touche"&1".
i go on lake, zoom as much as possible and my game is in windowed mode. So i think i have do all setting like it necessary. When i start the bot, it's write on the bot "cast" but it don't cast in game, then it search the bobber but it couldn't find it because it failed to cast it. When i cast manualy and start the bot after it search and find well the bobber and loot the fish, but when he try to cast it fail again, so the problem it's the bot failed to cast fishing. I have try to change the binding but no success.  (sorry if i make mistake, english is not easy to me)

**Comment by NaNraptor** [comment]
Try using the latest version of the bot and let me know if you still have the same problem
